name: meripseqpipe-1.0dev
channels:
  - r
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - openjdk=8.0.192
  - python=2.7.15
  - picard=2.21.6
  - fastqc=0.11.8
  - fastp=0.19.7
  - bedtools=2.27.1
  - ucsc-gtftogenepred=377
  - ucsc-fatotwobit=377
  - ucsc-facount=377
  - hisat2=2.1.0
  - bowtie2=2.2.5
  - bwa=0.7.17
  - star=2.6.1b
  - tophat=2.1.1
  - samtools=1.9
  - rseqc=2.6.4
  - macs2=2.1.2
  - meme=5.1.1
  - homer=4.9.1
  - dos2unix=7.4.1
  - r-base=3.5.1
  - bioconductor-edger=3.26.0
  - bioconductor-deseq2=1.22.1
  - igvtools=2.3.93
  - bioconductor-exomepeak=2.16.0
  - r-robustrankaggreg=1.1
  - perl=5.26.2
  - ucsc-genepredtobed=377
  - scipy=1.2.1
  - deeptools=3.1.3
  - ucsc-bigwigtowig=357
  - r-ggplot2=3.1.1
  - r-ggrepel=0.8.1
  - r-ggsci=2.9
  - r-pheatmap=1.0.12
  - r-dplyr=0.8.0.1
  - r-knitr=1.22
  - r-ggseqlogo=0.1
  - r-rmarkdown=1.10
  - subread=2.0.0 
  - pandoc=2.7.3
